python eval_math500.py \
    --scorer_type logprob \
    --model_path Qwen/Qwen2.5-7B-Instruct \
    --n_particles 8 \
    --max_steps 25 \
    --max_tokens_per_step 128 \
    --temperature 0.7 \
    --output_file math500_logprob_results.jsonl \
    --llm_device cuda:0 \
    --tp 2 \
    --gpu_mem 0.9 \
    --alpha 0.5 \
    --beta 1.0 \
    --rho 0.5 \
    --logprob_normalize
